In [2]:
import pandas as pd
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Bloque 1: Exploración inicial
## Ejercicio 1. Primera inspección
Carga el dataset y responde: ¿Cuántas filas y columnas tiene? ¿Cuáles son los tipos de datos de cada columna? ¿Cuánta memoria ocupa el DataFrame?

In [5]:
df.shape

(891, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Ejercicio 2. Estadísticas descriptivas
Genera un resumen estadístico de las variables numéricas. ¿Cuál es la edad media?
¿Y la tarifa media? ¿Hay algún valor que te llame la atención como posible anomalía?

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Ejercicio 3. Distribución de variables categóricas
¿Cuántos pasajeros hay de cada sexo? ¿Cuántos en cada clase? ¿Desde qué puerto embarcaron más pasajeros? Usa value_counts() para responder.

In [21]:
df.value_counts("Sex")

Sex
male      577
female    314
Name: count, dtype: int64

In [20]:
df.value_counts("Pclass")

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [22]:
df.value_counts("Embarked")

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

# Bloque 2: Diagnóstico de calidad de datos
## Ejercicio 4. Mapa de valores faltantes
Crea un informe que muestre para cada columna: número de valores faltantes, porcentaje del total, y tipo de dato. Ordena el resultado de mayor a menor porcentaje de missing

In [30]:

total_filas = len(df)

informe = pd.DataFrame({
    "valores_faltantes": df.isna().sum(),
    "porcentaje_faltante": df.isna().sum() / total_filas * 100,
    "dtype": df.dtypes
})

informe = informe.sort_values(by="porcentaje_faltante", ascending=False)

informe

             valores_faltantes  porcentaje_faltante    dtype
Cabin                      687            77.104377   object
Age                        177            19.865320  float64
Embarked                     2             0.224467   object
PassengerId                  0             0.000000    int64
Name                         0             0.000000   object
Pclass                       0             0.000000    int64
Survived                     0             0.000000    int64
Sex                          0             0.000000   object
Parch                        0             0.000000    int64
SibSp                        0             0.000000    int64
Fare                         0             0.000000  float64
Ticket                       0             0.000000   object

## Ejercicio 5. Análisis de la variable Cabin
La columna Cabin tiene muchos valores faltantes. Para los registros que sí tienen cabina, ¿puedes extraer la letra inicial (que indica la cubierta)? ¿Hay relación entre la cubierta y la clase del pasajero?

In [44]:
serie_cabin = df[df["Cabin"].notna()]
print(serie_cabin["Cabin"].str[0])
pd.crosstab(serie_cabin["Cabin"].str[0], df["Pclass"])

1      C
3      C
6      E
10     G
11     C
      ..
871    D
872    B
879    C
887    B
889    C
Name: Cabin, Length: 204, dtype: object

Pclass   1  2  3
Cabin
A       15  0  0
B       47  0  0
C       59  0  0
D       29  4  0
E       25  4  3
F        0  8  5
G        0  0  4
T        1  0  0

## Ejercicio 6. Detección de duplicados
¿Hay filas completamente duplicadas en el dataset? ¿Y duplicados parciales (mismo nombre y ticket)? Si los hay, ¿cómo los gestionarías?

In [50]:
df.drop_duplicates()
df.duplicated(subset=["Name","Ticket"]).sum()

np.int64(0)

## Ejercicio 7. Consistencia de datos
Verifica que los valores de Pclass estén en el rango esperado (1, 2, 3). ¿Hay algún pasajero con edad negativa o tarifa negativa? ¿Hay valores atípicos en la tarifa (outliers extremos)?